version: 2
jobs:
  build:
    working_directory: ~/foodplanner
    docker:
      - image: circleci/node:latest-browsers
      - image: mariadb:latest
    environment:
      CHROME_BIN: "/usr/bin/google-chrome"
      GITHUB_SECRET_FOOD:"none"
      FOOD_HOME:"~/foodplanner/server/"
      FOOD_CLIENT:"~/foodplanner/dist/"
      FOOD_TESTS:"~/foodplanner/test/"
      FOOD_ROOT:"~/foodplanner/"
      FOOD_DB_USERNAME:"food"
      FOOD_DB_PASSWORD:"plan"
      FOOD_DB_NAME:"food"
      FOOD_PORT:"22222"
      FOOD_EXTERNAL:"localhost"
      FOOD_MAILPW:"none"
      FOOD_UUID:"asdajsdlajiwdjjdibadj23hbsiu8szfhu2n23ud9s8fjs3rnun"
      ADMIN_DB_USERNAME:"root"
      ADMIN_DB_PASSWORD:""
      ADMIN_DB_PORT:"3307"
      ADMIN_DB_HOST:"localhost"
      DEVELOP:"true"
      DEV_PORT:"8080"
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: setup db
          command: node server/setup.js -y
      - run:
          name: run smoke tests
          command: |
            node ./server/index.js &
            touch test-log
            npm run-script test-ui > test-log
            cat test-log
            pkill -f "node.*server/index.js"
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml